### ISSUE TITLE
Vector Tiles Don't Draw Property in IE Edge

### ISSUE THREAD

**Issue by justingreco** [david-meza/park-locator#34]

**Comment by justingreco** [comment]
Use one of Esri's non-vector tile basemaps in IE Edge might be the best option.

**Comment by justingreco** [comment]
Not an issue when using the 4.0 beta version of the ArcGIS API

**Comment by justingreco** [comment]
Update, seems to be an issue with our vector tile base map, looks like Esri's will work.

**Comment by david-meza** [comment]
@justingreco Please check if this issue happens with older versions of Edge or if it only happens when using the bootcamp partition in Mac. Ideally, we will also want to check on a native machine.

**Comment by justingreco** [comment]
@david-meza Edge on my bootcamp is only at version 20.  Looks like I need to upgrade Windows 10 to build 1511 in order to get to version 25 of Edge.  Looks like latest version has some improvements to the WebGL API, which the vector tiles use.  Will let you know what happens after the upgrade

**Comment by justingreco** [comment]
Here is what it looks like in version 20 of Edge:
![capture](https://cloud.githubusercontent.com/assets/6587288/14931523/279b5346-0e3a-11e6-8d5d-b43a0bf23bae.PNG)

**Comment by justingreco** [comment]
Resolved by upgrading Windows 10 to build 1511
